#include <stdio.h>
#include "../holberton.h"
int main()
{
	int len;
	len = _printf("%%T = ", 4);
	len = _printf("%T\n", 4);
	len = _printf("%% T = ", 4);
	len = _printf("% T\n", 4);
	len = _printf("%%#T = ", 4);
	len = _printf("%#T\n", 4);
	len = _printf("%%+T = ", 4);
	len = _printf("%+T\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +T = ", 4);
	len = _printf("% +T\n", 4);
	len = _printf("%% #T = ", 4);
	len = _printf("% #T\n", 4);
	len = _printf("%%+ T = ", 4);
	len = _printf("%+ T\n", 4);
	len = _printf("%%+#T = ", 4);
	len = _printf("%+#T\n", 4);
	len = _printf("%%# T = ", 4);
	len = _printf("%# T\n", 4);
	len = _printf("%%#+T = ", 4);
	len = _printf("%#+T\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +#T = ", 4);
	len = _printf("% +#T\n", 4);
	len = _printf("%% #+T = ", 4);
	len = _printf("% #+T\n", 4);
	len = _printf("%%+# T = ", 4);
	len = _printf("%+# T\n", 4);
	len = _printf("%%+ #T = ", 4);
	len = _printf("%+ #T\n", 4);
	len = _printf("%%#+ T = ", 4);
	len = _printf("%#+ T\n", 4);
	len = _printf("%%# +T = ", 4);
	len = _printf("%# +T\n", 4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");


	len = _printf("%%u = ", 4);
	len = _printf("%u\n", 4);
	len = _printf("%% u = ", 4);
	len = _printf("% u\n", 4);
	len = _printf("%%#u = ", 4);
	len = _printf("%#u\n", 4);
	len = _printf("%%+u = ", 4);
	len = _printf("%+u\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +u = ", 4);
	len = _printf("% +u\n", 4);
	len = _printf("%% #u = ", 4);
	len = _printf("% #u\n", 4);
	len = _printf("%%+ u = ", 4);
	len = _printf("%+ u\n", 4);
	len = _printf("%%+#u = ", 4);
	len = _printf("%+#u\n", 4);
	len = _printf("%%# u = ", 4);
	len = _printf("%# u\n", 4);
	len = _printf("%%#+u = ", 4);
	len = _printf("%#+u\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +#u = ", 4);
	len = _printf("% +#u\n", 4);
	len = _printf("%% #+u = ", 4);
	len = _printf("% #+u\n", 4);
	len = _printf("%%+# u = ", 4);
	len = _printf("%+# u\n", 4);
	len = _printf("%%+ #u = ", 4);
	len = _printf("%+ #u\n", 4);
	len = _printf("%%#+ u = ", 4);
	len = _printf("%#+ u\n", 4);
	len = _printf("%%# +u = ", 4);
	len = _printf("%# +u\n", 4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%o = ", 4);
	len = _printf("%o\n", 4);
	len = _printf("%% o = ", 4);
	len = _printf("% o\n", 4);
	len = _printf("%%#o = ", 4);
	len = _printf("%#o\n", 4);
	len = _printf("%%+o = ", 4);
	len = _printf("%+o\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +o = ", 4);
	len = _printf("% +o\n", 4);
	len = _printf("%% #o = ", 4);
	len = _printf("% #o\n", 4);
	len = _printf("%%+ o = ", 4);
	len = _printf("%+ o\n", 4);
	len = _printf("%%+#o = ", 4);
	len = _printf("%+#o\n", 4);
	len = _printf("%%# o = ", 4);
	len = _printf("%# o\n", 4);
	len = _printf("%%#+o = ", 4);
	len = _printf("%#+o\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +#o = ", 4);
	len = _printf("% +#o\n", 4);
	len = _printf("%% #+o = ", 4);
	len = _printf("% #+o\n", 4);
	len = _printf("%%+# o = ", 4);
	len = _printf("%+# o\n", 4);
	len = _printf("%%+ #o = ", 4);
	len = _printf("%+ #o\n", 4);
	len = _printf("%%#+ o = ", 4);
	len = _printf("%#+ o\n", 4);
	len = _printf("%%# +o = ", 4);
	len = _printf("%# +o\n", 4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%x = ", 4);
	len = _printf("%x\n", 4);
	len = _printf("%% x = ", 4);
	len = _printf("% x\n", 4);
	len = _printf("%%#x = ", 4);
	len = _printf("%#x\n", 4);
	len = _printf("%%+x = ", 4);
	len = _printf("%+x\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +x = ", 4);
	len = _printf("% +x\n", 4);
	len = _printf("%% #x = ", 4);
	len = _printf("% #x\n", 4);
	len = _printf("%%+ x = ", 4);
	len = _printf("%+ x\n", 4);
	len = _printf("%%+#x = ", 4);
	len = _printf("%+#x\n", 4);
	len = _printf("%%# x = ", 4);
	len = _printf("%# x\n", 4);
	len = _printf("%%#+x = ", 4);
	len = _printf("%#+x\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +#x = ", 4);
	len = _printf("% +#x\n", 4);
	len = _printf("%% #+x = ", 4);
	len = _printf("% #+x\n", 4);
	len = _printf("%%+# x = ", 4);
	len = _printf("%+# x\n", 4);
	len = _printf("%%+ #x = ", 4);
	len = _printf("%+ #x\n", 4);
	len = _printf("%%#+ x = ", 4);
	len = _printf("%#+ x\n", 4);
	len = _printf("%%# +x = ", 4);
	len = _printf("%# +x\n", 4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%X = ", 4);
	len = _printf("%X\n", 4);
	len = _printf("%% X = ", 4);
	len = _printf("% X\n", 4);
	len = _printf("%%#X = ", 4);
	len = _printf("%#X\n", 4);
	len = _printf("%%+X = ", 4);
	len = _printf("%+X\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +X = ", 4);
	len = _printf("% +X\n", 4);
	len = _printf("%% #X = ", 4);
	len = _printf("% #X\n", 4);
	len = _printf("%%+ X = ", 4);
	len = _printf("%+ X\n", 4);
	len = _printf("%%+#X = ", 4);
	len = _printf("%+#X\n", 4);
	len = _printf("%%# X = ", 4);
	len = _printf("%# X\n", 4);
	len = _printf("%%#+X = ", 4);
	len = _printf("%#+X\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +#X = ", 4);
	len = _printf("% +#X\n", 4);
	len = _printf("%% #+X = ", 4);
	len = _printf("% #+X\n", 4);
	len = _printf("%%+# X = ", 4);
	len = _printf("%+# X\n", 4);
	len = _printf("%%+ #X = ", 4);
	len = _printf("%+ #X\n", 4);
	len = _printf("%%#+ X = ", 4);
	len = _printf("%#+ X\n", 4);
	len = _printf("%%# +X = ", 4);
	len = _printf("%# +X\n", 4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");



	len = _printf("%%c = ", 'f');
	len = _printf("%c\n", 'f');
	len = _printf("%% c = ", 'f');
	len = _printf("% c\n", 'f');
	len = _printf("%%#c = ", 'f');
	len = _printf("%#c\n", 'f');
	len = _printf("%%+c = ", 'f');
	len = _printf("%+c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("%% +c = ", 'f');
	len = _printf("% +c\n", 'f');
	len = _printf("%% #c = ", 'f');
	len = _printf("% #c\n", 'f');
	len = _printf("%%+ c = ", 'f');
	len = _printf("%+ c\n", 'f');
	len = _printf("%%+#c = ", 'f');
	len = _printf("%+#c\n", 'f');
	len = _printf("%%# c = ", 'f');
	len = _printf("%# c\n", 'f');
	len = _printf("%%#+c = ", 'f');
	len = _printf("%#+c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("%% +#c = ", 'f');
	len = _printf("% +#c\n", 'f');
	len = _printf("%% #+c = ", 'f');
	len = _printf("% #+c\n", 'f');
	len = _printf("%%+# c = ", 'f');
	len = _printf("%+# c\n", 'f');
	len = _printf("%%+ #c = ", 'f');
	len = _printf("%+ #c\n", 'f');
	len = _printf("%%#+ c = ", 'f');
	len = _printf("%#+ c\n", 'f');
	len = _printf("%%# +c = ", 'f');
	len = _printf("%# +c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");


	len = _printf("%%% = ", 4);
	len = _printf("%%\n", 4);
	len = _printf("%% % = ", 4);
	len = _printf("% %\n", 4);
	len = _printf("%%#% = ", 4);
	len = _printf("%#%\n", 4);
	len = _printf("%%+% = ", 4);
	len = _printf("%+%\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +% = ", 4);
	len = _printf("% +%\n", 4);
	len = _printf("%% #% = ", 4);
	len = _printf("% #%\n", 4);
	len = _printf("%%+ % = ", 4);
	len = _printf("%+ %\n", 4);
	len = _printf("%%+#% = ", 4);
	len = _printf("%+#%\n", 4);
	len = _printf("%%# % = ", 4);
	len = _printf("%# %\n", 4);
	len = _printf("%%#+% = ", 4);
	len = _printf("%#+%\n", 4);
	len = _printf("--------------------\n");
	len = _printf("%% +#% = ", 4);
	len = _printf("% +#%\n", 4);
	len = _printf("%% #+% = ", 4);
	len = _printf("% #+%\n", 4);
	len = _printf("%%+# % = ", 4);
	len = _printf("%+# %\n", 4);
	len = _printf("%%+ #% = ", 4);
	len = _printf("%+ #%\n", 4);
	len = _printf("%%#+ % = ", 4);
	len = _printf("%#+ %\n", 4);
	len = _printf("%%# +% = ", 4);
	len = _printf("%# +%\n", 4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");





	len = _printf("%%T = ", -4);
	len = _printf("%T\n", -4);
	len = _printf("%% T = ", -4);
	len = _printf("% T\n", -4);
	len = _printf("%%#T = ", -4);
	len = _printf("%#T\n", -4);
	len = _printf("%%+T = ", -4);
	len = _printf("%+T\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +T = ", -4);
	len = _printf("% +T\n", -4);
	len = _printf("%% #T = ", -4);
	len = _printf("% #T\n", -4);
	len = _printf("%%+ T = ", -4);
	len = _printf("%+ T\n", -4);
	len = _printf("%%+#T = ", -4);
	len = _printf("%+#T\n", -4);
	len = _printf("%%# T = ", -4);
	len = _printf("%# T\n", -4);
	len = _printf("%%#+T = ", -4);
	len = _printf("%#+T\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +#T = ", -4);
	len = _printf("% +#T\n", -4);
	len = _printf("%% #+T = ", -4);
	len = _printf("% #+T\n", -4);
	len = _printf("%%+# T = ", -4);
	len = _printf("%+# T\n", -4);
	len = _printf("%%+ #T = ", -4);
	len = _printf("%+ #T\n", -4);
	len = _printf("%%#+ T = ", -4);
	len = _printf("%#+ T\n", -4);
	len = _printf("%%# +T = ", -4);
	len = _printf("%# +T\n", -4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");


	len = _printf("%%u = ", -4);
	len = _printf("%u\n", -4);
	len = _printf("%% u = ", -4);
	len = _printf("% u\n", -4);
	len = _printf("%%#u = ", -4);
	len = _printf("%#u\n", -4);
	len = _printf("%%+u = ", -4);
	len = _printf("%+u\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +u = ", -4);
	len = _printf("% +u\n", -4);
	len = _printf("%% #u = ", -4);
	len = _printf("% #u\n", -4);
	len = _printf("%%+ u = ", -4);
	len = _printf("%+ u\n", -4);
	len = _printf("%%+#u = ", -4);
	len = _printf("%+#u\n", -4);
	len = _printf("%%# u = ", -4);
	len = _printf("%# u\n", -4);
	len = _printf("%%#+u = ", -4);
	len = _printf("%#+u\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +#u = ", -4);
	len = _printf("% +#u\n", -4);
	len = _printf("%% #+u = ", -4);
	len = _printf("% #+u\n", -4);
	len = _printf("%%+# u = ", -4);
	len = _printf("%+# u\n", -4);
	len = _printf("%%+ #u = ", -4);
	len = _printf("%+ #u\n", -4);
	len = _printf("%%#+ u = ", -4);
	len = _printf("%#+ u\n", -4);
	len = _printf("%%# +u = ", -4);
	len = _printf("%# +u\n", -4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%o = ", -4);
	len = _printf("%o\n", -4);
	len = _printf("%% o = ", -4);
	len = _printf("% o\n", -4);
	len = _printf("%%#o = ", -4);
	len = _printf("%#o\n", -4);
	len = _printf("%%+o = ", -4);
	len = _printf("%+o\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +o = ", -4);
	len = _printf("% +o\n", -4);
	len = _printf("%% #o = ", -4);
	len = _printf("% #o\n", -4);
	len = _printf("%%+ o = ", -4);
	len = _printf("%+ o\n", -4);
	len = _printf("%%+#o = ", -4);
	len = _printf("%+#o\n", -4);
	len = _printf("%%# o = ", -4);
	len = _printf("%# o\n", -4);
	len = _printf("%%#+o = ", -4);
	len = _printf("%#+o\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +#o = ", -4);
	len = _printf("% +#o\n", -4);
	len = _printf("%% #+o = ", -4);
	len = _printf("% #+o\n", -4);
	len = _printf("%%+# o = ", -4);
	len = _printf("%+# o\n", -4);
	len = _printf("%%+ #o = ", -4);
	len = _printf("%+ #o\n", -4);
	len = _printf("%%#+ o = ", -4);
	len = _printf("%#+ o\n", -4);
	len = _printf("%%# +o = ", -4);
	len = _printf("%# +o\n", -4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%x = ", -4);
	len = _printf("%x\n", -4);
	len = _printf("%% x = ", -4);
	len = _printf("% x\n", -4);
	len = _printf("%%#x = ", -4);
	len = _printf("%#x\n", -4);
	len = _printf("%%+x = ", -4);
	len = _printf("%+x\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +x = ", -4);
	len = _printf("% +x\n", -4);
	len = _printf("%% #x = ", -4);
	len = _printf("% #x\n", -4);
	len = _printf("%%+ x = ", -4);
	len = _printf("%+ x\n", -4);
	len = _printf("%%+#x = ", -4);
	len = _printf("%+#x\n", -4);
	len = _printf("%%# x = ", -4);
	len = _printf("%# x\n", -4);
	len = _printf("%%#+x = ", -4);
	len = _printf("%#+x\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +#x = ", -4);
	len = _printf("% +#x\n", -4);
	len = _printf("%% #+x = ", -4);
	len = _printf("% #+x\n", -4);
	len = _printf("%%+# x = ", -4);
	len = _printf("%+# x\n", -4);
	len = _printf("%%+ #x = ", -4);
	len = _printf("%+ #x\n", -4);
	len = _printf("%%#+ x = ", -4);
	len = _printf("%#+ x\n", -4);
	len = _printf("%%# +x = ", -4);
	len = _printf("%# +x\n", -4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%X = ", -4);
	len = _printf("%X\n", -4);
	len = _printf("%% X = ", -4);
	len = _printf("% X\n", -4);
	len = _printf("%%#X = ", -4);
	len = _printf("%#X\n", -4);
	len = _printf("%%+X = ", -4);
	len = _printf("%+X\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +X = ", -4);
	len = _printf("% +X\n", -4);
	len = _printf("%% #X = ", -4);
	len = _printf("% #X\n", -4);
	len = _printf("%%+ X = ", -4);
	len = _printf("%+ X\n", -4);
	len = _printf("%%+#X = ", -4);
	len = _printf("%+#X\n", -4);
	len = _printf("%%# X = ", -4);
	len = _printf("%# X\n", -4);
	len = _printf("%%#+X = ", -4);
	len = _printf("%#+X\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +#X = ", -4);
	len = _printf("% +#X\n", -4);
	len = _printf("%% #+X = ", -4);
	len = _printf("% #+X\n", -4);
	len = _printf("%%+# X = ", -4);
	len = _printf("%+# X\n", -4);
	len = _printf("%%+ #X = ", -4);
	len = _printf("%+ #X\n", -4);
	len = _printf("%%#+ X = ", -4);
	len = _printf("%#+ X\n", -4);
	len = _printf("%%# +X = ", -4);
	len = _printf("%# +X\n", -4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");



	len = _printf("%%c = ", 'f');
	len = _printf("%c\n", 'f');
	len = _printf("%% c = ", 'f');
	len = _printf("% c\n", 'f');
	len = _printf("%%#c = ", 'f');
	len = _printf("%#c\n", 'f');
	len = _printf("%%+c = ", 'f');
	len = _printf("%+c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("%% +c = ", 'f');
	len = _printf("% +c\n", 'f');
	len = _printf("%% #c = ", 'f');
	len = _printf("% #c\n", 'f');
	len = _printf("%%+ c = ", 'f');
	len = _printf("%+ c\n", 'f');
	len = _printf("%%+#c = ", 'f');
	len = _printf("%+#c\n", 'f');
	len = _printf("%%# c = ", 'f');
	len = _printf("%# c\n", 'f');
	len = _printf("%%#+c = ", 'f');
	len = _printf("%#+c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("%% +#c = ", 'f');
	len = _printf("% +#c\n", 'f');
	len = _printf("%% #+c = ", 'f');
	len = _printf("% #+c\n", 'f');
	len = _printf("%%+# c = ", 'f');
	len = _printf("%+# c\n", 'f');
	len = _printf("%%+ #c = ", 'f');
	len = _printf("%+ #c\n", 'f');
	len = _printf("%%#+ c = ", 'f');
	len = _printf("%#+ c\n", 'f');
	len = _printf("%%# +c = ", 'f');
	len = _printf("%# +c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");


	len = _printf("%%% = ", -4);
	len = _printf("%%\n", -4);
	len = _printf("%% % = ", -4);
	len = _printf("% %\n", -4);
	len = _printf("%%#% = ", -4);
	len = _printf("%#%\n", -4);
	len = _printf("%%+% = ", -4);
	len = _printf("%+%\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +% = ", -4);
	len = _printf("% +%\n", -4);
	len = _printf("%% #% = ", -4);
	len = _printf("% #%\n", -4);
	len = _printf("%%+ % = ", -4);
	len = _printf("%+ %\n", -4);
	len = _printf("%%+#% = ", -4);
	len = _printf("%+#%\n", -4);
	len = _printf("%%# % = ", -4);
	len = _printf("%# %\n", -4);
	len = _printf("%%#+% = ", -4);
	len = _printf("%#+%\n", -4);
	len = _printf("--------------------\n");
	len = _printf("%% +#% = ", -4);
	len = _printf("% +#%\n", -4);
	len = _printf("%% #+% = ", -4);
	len = _printf("% #+%\n", -4);
	len = _printf("%%+# % = ", -4);
	len = _printf("%+# %\n", -4);
	len = _printf("%%+ #% = ", -4);
	len = _printf("%+ #%\n", -4);
	len = _printf("%%#+ % = ", -4);
	len = _printf("%#+ %\n", -4);
	len = _printf("%%# +% = ", -4);
	len = _printf("%# +%\n", -4);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");



	len = _printf("%%T = ", 0);
	len = _printf("%T\n", 0);
	len = _printf("%% T = ", 0);
	len = _printf("% T\n", 0);
	len = _printf("%%#T = ", 0);
	len = _printf("%#T\n", 0);
	len = _printf("%%+T = ", 0);
	len = _printf("%+T\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +T = ", 0);
	len = _printf("% +T\n", 0);
	len = _printf("%% #T = ", 0);
	len = _printf("% #T\n", 0);
	len = _printf("%%+ T = ", 0);
	len = _printf("%+ T\n", 0);
	len = _printf("%%+#T = ", 0);
	len = _printf("%+#T\n", 0);
	len = _printf("%%# T = ", 0);
	len = _printf("%# T\n", 0);
	len = _printf("%%#+T = ", 0);
	len = _printf("%#+T\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +#T = ", 0);
	len = _printf("% +#T\n", 0);
	len = _printf("%% #+T = ", 0);
	len = _printf("% #+T\n", 0);
	len = _printf("%%+# T = ", 0);
	len = _printf("%+# T\n", 0);
	len = _printf("%%+ #T = ", 0);
	len = _printf("%+ #T\n", 0);
	len = _printf("%%#+ T = ", 0);
	len = _printf("%#+ T\n", 0);
	len = _printf("%%# +T = ", 0);
	len = _printf("%# +T\n", 0);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");


	len = _printf("%%u = ", 0);
	len = _printf("%u\n", 0);
	len = _printf("%% u = ", 0);
	len = _printf("% u\n", 0);
	len = _printf("%%#u = ", 0);
	len = _printf("%#u\n", 0);
	len = _printf("%%+u = ", 0);
	len = _printf("%+u\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +u = ", 0);
	len = _printf("% +u\n", 0);
	len = _printf("%% #u = ", 0);
	len = _printf("% #u\n", 0);
	len = _printf("%%+ u = ", 0);
	len = _printf("%+ u\n", 0);
	len = _printf("%%+#u = ", 0);
	len = _printf("%+#u\n", 0);
	len = _printf("%%# u = ", 0);
	len = _printf("%# u\n", 0);
	len = _printf("%%#+u = ", 0);
	len = _printf("%#+u\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +#u = ", 0);
	len = _printf("% +#u\n", 0);
	len = _printf("%% #+u = ", 0);
	len = _printf("% #+u\n", 0);
	len = _printf("%%+# u = ", 0);
	len = _printf("%+# u\n", 0);
	len = _printf("%%+ #u = ", 0);
	len = _printf("%+ #u\n", 0);
	len = _printf("%%#+ u = ", 0);
	len = _printf("%#+ u\n", 0);
	len = _printf("%%# +u = ", 0);
	len = _printf("%# +u\n", 0);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%o = ", 0);
	len = _printf("%o\n", 0);
	len = _printf("%% o = ", 0);
	len = _printf("% o\n", 0);
	len = _printf("%%#o = ", 0);
	len = _printf("%#o\n", 0);
	len = _printf("%%+o = ", 0);
	len = _printf("%+o\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +o = ", 0);
	len = _printf("% +o\n", 0);
	len = _printf("%% #o = ", 0);
	len = _printf("% #o\n", 0);
	len = _printf("%%+ o = ", 0);
	len = _printf("%+ o\n", 0);
	len = _printf("%%+#o = ", 0);
	len = _printf("%+#o\n", 0);
	len = _printf("%%# o = ", 0);
	len = _printf("%# o\n", 0);
	len = _printf("%%#+o = ", 0);
	len = _printf("%#+o\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +#o = ", 0);
	len = _printf("% +#o\n", 0);
	len = _printf("%% #+o = ", 0);
	len = _printf("% #+o\n", 0);
	len = _printf("%%+# o = ", 0);
	len = _printf("%+# o\n", 0);
	len = _printf("%%+ #o = ", 0);
	len = _printf("%+ #o\n", 0);
	len = _printf("%%#+ o = ", 0);
	len = _printf("%#+ o\n", 0);
	len = _printf("%%# +o = ", 0);
	len = _printf("%# +o\n", 0);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%x = ", 0);
	len = _printf("%x\n", 0);
	len = _printf("%% x = ", 0);
	len = _printf("% x\n", 0);
	len = _printf("%%#x = ", 0);
	len = _printf("%#x\n", 0);
	len = _printf("%%+x = ", 0);
	len = _printf("%+x\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +x = ", 0);
	len = _printf("% +x\n", 0);
	len = _printf("%% #x = ", 0);
	len = _printf("% #x\n", 0);
	len = _printf("%%+ x = ", 0);
	len = _printf("%+ x\n", 0);
	len = _printf("%%+#x = ", 0);
	len = _printf("%+#x\n", 0);
	len = _printf("%%# x = ", 0);
	len = _printf("%# x\n", 0);
	len = _printf("%%#+x = ", 0);
	len = _printf("%#+x\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +#x = ", 0);
	len = _printf("% +#x\n", 0);
	len = _printf("%% #+x = ", 0);
	len = _printf("% #+x\n", 0);
	len = _printf("%%+# x = ", 0);
	len = _printf("%+# x\n", 0);
	len = _printf("%%+ #x = ", 0);
	len = _printf("%+ #x\n", 0);
	len = _printf("%%#+ x = ", 0);
	len = _printf("%#+ x\n", 0);
	len = _printf("%%# +x = ", 0);
	len = _printf("%# +x\n", 0);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");

	len = _printf("%%X = ", 0);
	len = _printf("%X\n", 0);
	len = _printf("%% X = ", 0);
	len = _printf("% X\n", 0);
	len = _printf("%%#X = ", 0);
	len = _printf("%#X\n", 0);
	len = _printf("%%+X = ", 0);
	len = _printf("%+X\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +X = ", 0);
	len = _printf("% +X\n", 0);
	len = _printf("%% #X = ", 0);
	len = _printf("% #X\n", 0);
	len = _printf("%%+ X = ", 0);
	len = _printf("%+ X\n", 0);
	len = _printf("%%+#X = ", 0);
	len = _printf("%+#X\n", 0);
	len = _printf("%%# X = ", 0);
	len = _printf("%# X\n", 0);
	len = _printf("%%#+X = ", 0);
	len = _printf("%#+X\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +#X = ", 0);
	len = _printf("% +#X\n", 0);
	len = _printf("%% #+X = ", 0);
	len = _printf("% #+X\n", 0);
	len = _printf("%%+# X = ", 0);
	len = _printf("%+# X\n", 0);
	len = _printf("%%+ #X = ", 0);
	len = _printf("%+ #X\n", 0);
	len = _printf("%%#+ X = ", 0);
	len = _printf("%#+ X\n", 0);
	len = _printf("%%# +X = ", 0);
	len = _printf("%# +X\n", 0);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");



	len = _printf("%%c = ", 'f');
	len = _printf("%c\n", 'f');
	len = _printf("%% c = ", 'f');
	len = _printf("% c\n", 'f');
	len = _printf("%%#c = ", 'f');
	len = _printf("%#c\n", 'f');
	len = _printf("%%+c = ", 'f');
	len = _printf("%+c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("%% +c = ", 'f');
	len = _printf("% +c\n", 'f');
	len = _printf("%% #c = ", 'f');
	len = _printf("% #c\n", 'f');
	len = _printf("%%+ c = ", 'f');
	len = _printf("%+ c\n", 'f');
	len = _printf("%%+#c = ", 'f');
	len = _printf("%+#c\n", 'f');
	len = _printf("%%# c = ", 'f');
	len = _printf("%# c\n", 'f');
	len = _printf("%%#+c = ", 'f');
	len = _printf("%#+c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("%% +#c = ", 'f');
	len = _printf("% +#c\n", 'f');
	len = _printf("%% #+c = ", 'f');
	len = _printf("% #+c\n", 'f');
	len = _printf("%%+# c = ", 'f');
	len = _printf("%+# c\n", 'f');
	len = _printf("%%+ #c = ", 'f');
	len = _printf("%+ #c\n", 'f');
	len = _printf("%%#+ c = ", 'f');
	len = _printf("%#+ c\n", 'f');
	len = _printf("%%# +c = ", 'f');
	len = _printf("%# +c\n", 'f');
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");


	len = _printf("%%% = ", 0);
	len = _printf("%%\n", 0);
	len = _printf("%% % = ", 0);
	len = _printf("% %\n", 0);
	len = _printf("%%#% = ", 0);
	len = _printf("%#%\n", 0);
	len = _printf("%%+% = ", 0);
	len = _printf("%+%\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +% = ", 0);
	len = _printf("% +%\n", 0);
	len = _printf("%% #% = ", 0);
	len = _printf("% #%\n", 0);
	len = _printf("%%+ % = ", 0);
	len = _printf("%+ %\n", 0);
	len = _printf("%%+#% = ", 0);
	len = _printf("%+#%\n", 0);
	len = _printf("%%# % = ", 0);
	len = _printf("%# %\n", 0);
	len = _printf("%%#+% = ", 0);
	len = _printf("%#+%\n", 0);
	len = _printf("--------------------\n");
	len = _printf("%% +#% = ", 0);
	len = _printf("% +#%\n", 0);
	len = _printf("%% #+% = ", 0);
	len = _printf("% #+%\n", 0);
	len = _printf("%%+# % = ", 0);
	len = _printf("%+# %\n", 0);
	len = _printf("%%+ #% = ", 0);
	len = _printf("%+ #%\n", 0);
	len = _printf("%%#+ % = ", 0);
	len = _printf("%#+ %\n", 0);
	len = _printf("%%# +% = ", 0);
	len = _printf("%# +%\n", 0);
	len = _printf("--------------------\n");
	len = _printf("--------------------\n");



	return (len);
}
