#include <stdio.h>
#include "../holberton.h"
int main()
{
	int len;
	len = printf("%%T = ", 4);
	len = printf("%T\n", 4);
	len = printf("%% T = ", 4);
	len = printf("% T\n", 4);
	len = printf("%%#T = ", 4);
	len = printf("%#T\n", 4);
	len = printf("%%+T = ", 4);
	len = printf("%+T\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +T = ", 4);
	len = printf("% +T\n", 4);
	len = printf("%% #T = ", 4);
	len = printf("% #T\n", 4);
	len = printf("%%+ T = ", 4);
	len = printf("%+ T\n", 4);
	len = printf("%%+#T = ", 4);
	len = printf("%+#T\n", 4);
	len = printf("%%# T = ", 4);
	len = printf("%# T\n", 4);
	len = printf("%%#+T = ", 4);
	len = printf("%#+T\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#T = ", 4);
	len = printf("% +#T\n", 4);
	len = printf("%% #+T = ", 4);
	len = printf("% #+T\n", 4);
	len = printf("%%+# T = ", 4);
	len = printf("%+# T\n", 4);
	len = printf("%%+ #T = ", 4);
	len = printf("%+ #T\n", 4);
	len = printf("%%#+ T = ", 4);
	len = printf("%#+ T\n", 4);
	len = printf("%%# +T = ", 4);
	len = printf("%# +T\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");


	len = printf("%%u = ", 4);
	len = printf("%u\n", 4);
	len = printf("%% u = ", 4);
	len = printf("% u\n", 4);
	len = printf("%%#u = ", 4);
	len = printf("%#u\n", 4);
	len = printf("%%+u = ", 4);
	len = printf("%+u\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +u = ", 4);
	len = printf("% +u\n", 4);
	len = printf("%% #u = ", 4);
	len = printf("% #u\n", 4);
	len = printf("%%+ u = ", 4);
	len = printf("%+ u\n", 4);
	len = printf("%%+#u = ", 4);
	len = printf("%+#u\n", 4);
	len = printf("%%# u = ", 4);
	len = printf("%# u\n", 4);
	len = printf("%%#+u = ", 4);
	len = printf("%#+u\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#u = ", 4);
	len = printf("% +#u\n", 4);
	len = printf("%% #+u = ", 4);
	len = printf("% #+u\n", 4);
	len = printf("%%+# u = ", 4);
	len = printf("%+# u\n", 4);
	len = printf("%%+ #u = ", 4);
	len = printf("%+ #u\n", 4);
	len = printf("%%#+ u = ", 4);
	len = printf("%#+ u\n", 4);
	len = printf("%%# +u = ", 4);
	len = printf("%# +u\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%o = ", 4);
	len = printf("%o\n", 4);
	len = printf("%% o = ", 4);
	len = printf("% o\n", 4);
	len = printf("%%#o = ", 4);
	len = printf("%#o\n", 4);
	len = printf("%%+o = ", 4);
	len = printf("%+o\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +o = ", 4);
	len = printf("% +o\n", 4);
	len = printf("%% #o = ", 4);
	len = printf("% #o\n", 4);
	len = printf("%%+ o = ", 4);
	len = printf("%+ o\n", 4);
	len = printf("%%+#o = ", 4);
	len = printf("%+#o\n", 4);
	len = printf("%%# o = ", 4);
	len = printf("%# o\n", 4);
	len = printf("%%#+o = ", 4);
	len = printf("%#+o\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#o = ", 4);
	len = printf("% +#o\n", 4);
	len = printf("%% #+o = ", 4);
	len = printf("% #+o\n", 4);
	len = printf("%%+# o = ", 4);
	len = printf("%+# o\n", 4);
	len = printf("%%+ #o = ", 4);
	len = printf("%+ #o\n", 4);
	len = printf("%%#+ o = ", 4);
	len = printf("%#+ o\n", 4);
	len = printf("%%# +o = ", 4);
	len = printf("%# +o\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%x = ", 4);
	len = printf("%x\n", 4);
	len = printf("%% x = ", 4);
	len = printf("% x\n", 4);
	len = printf("%%#x = ", 4);
	len = printf("%#x\n", 4);
	len = printf("%%+x = ", 4);
	len = printf("%+x\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +x = ", 4);
	len = printf("% +x\n", 4);
	len = printf("%% #x = ", 4);
	len = printf("% #x\n", 4);
	len = printf("%%+ x = ", 4);
	len = printf("%+ x\n", 4);
	len = printf("%%+#x = ", 4);
	len = printf("%+#x\n", 4);
	len = printf("%%# x = ", 4);
	len = printf("%# x\n", 4);
	len = printf("%%#+x = ", 4);
	len = printf("%#+x\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#x = ", 4);
	len = printf("% +#x\n", 4);
	len = printf("%% #+x = ", 4);
	len = printf("% #+x\n", 4);
	len = printf("%%+# x = ", 4);
	len = printf("%+# x\n", 4);
	len = printf("%%+ #x = ", 4);
	len = printf("%+ #x\n", 4);
	len = printf("%%#+ x = ", 4);
	len = printf("%#+ x\n", 4);
	len = printf("%%# +x = ", 4);
	len = printf("%# +x\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%X = ", 4);
	len = printf("%X\n", 4);
	len = printf("%% X = ", 4);
	len = printf("% X\n", 4);
	len = printf("%%#X = ", 4);
	len = printf("%#X\n", 4);
	len = printf("%%+X = ", 4);
	len = printf("%+X\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +X = ", 4);
	len = printf("% +X\n", 4);
	len = printf("%% #X = ", 4);
	len = printf("% #X\n", 4);
	len = printf("%%+ X = ", 4);
	len = printf("%+ X\n", 4);
	len = printf("%%+#X = ", 4);
	len = printf("%+#X\n", 4);
	len = printf("%%# X = ", 4);
	len = printf("%# X\n", 4);
	len = printf("%%#+X = ", 4);
	len = printf("%#+X\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#X = ", 4);
	len = printf("% +#X\n", 4);
	len = printf("%% #+X = ", 4);
	len = printf("% #+X\n", 4);
	len = printf("%%+# X = ", 4);
	len = printf("%+# X\n", 4);
	len = printf("%%+ #X = ", 4);
	len = printf("%+ #X\n", 4);
	len = printf("%%#+ X = ", 4);
	len = printf("%#+ X\n", 4);
	len = printf("%%# +X = ", 4);
	len = printf("%# +X\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");



	len = printf("%%c = ", 'f');
	len = printf("%c\n", 'f');
	len = printf("%% c = ", 'f');
	len = printf("% c\n", 'f');
	len = printf("%%#c = ", 'f');
	len = printf("%#c\n", 'f');
	len = printf("%%+c = ", 'f');
	len = printf("%+c\n", 'f');
	len = printf("--------------------\n");
	len = printf("%% +c = ", 'f');
	len = printf("% +c\n", 'f');
	len = printf("%% #c = ", 'f');
	len = printf("% #c\n", 'f');
	len = printf("%%+ c = ", 'f');
	len = printf("%+ c\n", 'f');
	len = printf("%%+#c = ", 'f');
	len = printf("%+#c\n", 'f');
	len = printf("%%# c = ", 'f');
	len = printf("%# c\n", 'f');
	len = printf("%%#+c = ", 'f');
	len = printf("%#+c\n", 'f');
	len = printf("--------------------\n");
	len = printf("%% +#c = ", 'f');
	len = printf("% +#c\n", 'f');
	len = printf("%% #+c = ", 'f');
	len = printf("% #+c\n", 'f');
	len = printf("%%+# c = ", 'f');
	len = printf("%+# c\n", 'f');
	len = printf("%%+ #c = ", 'f');
	len = printf("%+ #c\n", 'f');
	len = printf("%%#+ c = ", 'f');
	len = printf("%#+ c\n", 'f');
	len = printf("%%# +c = ", 'f');
	len = printf("%# +c\n", 'f');
	len = printf("--------------------\n");
	len = printf("--------------------\n");


	len = printf("%%% = ", 4);
	len = printf("%%\n", 4);
	len = printf("%% % = ", 4);
	len = printf("% %\n", 4);
	len = printf("%%#% = ", 4);
	len = printf("%#%\n", 4);
	len = printf("%%+% = ", 4);
	len = printf("%+%\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +% = ", 4);
	len = printf("% +%\n", 4);
	len = printf("%% #% = ", 4);
	len = printf("% #%\n", 4);
	len = printf("%%+ % = ", 4);
	len = printf("%+ %\n", 4);
	len = printf("%%+#% = ", 4);
	len = printf("%+#%\n", 4);
	len = printf("%%# % = ", 4);
	len = printf("%# %\n", 4);
	len = printf("%%#+% = ", 4);
	len = printf("%#+%\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#% = ", 4);
	len = printf("% +#%\n", 4);
	len = printf("%% #+% = ", 4);
	len = printf("% #+%\n", 4);
	len = printf("%%+# % = ", 4);
	len = printf("%+# %\n", 4);
	len = printf("%%+ #% = ", 4);
	len = printf("%+ #%\n", 4);
	len = printf("%%#+ % = ", 4);
	len = printf("%#+ %\n", 4);
	len = printf("%%# +% = ", 4);
	len = printf("%# +%\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");





	len = printf("%%T = ", -4);
	len = printf("%T\n", -4);
	len = printf("%% T = ", -4);
	len = printf("% T\n", -4);
	len = printf("%%#T = ", -4);
	len = printf("%#T\n", -4);
	len = printf("%%+T = ", -4);
	len = printf("%+T\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +T = ", -4);
	len = printf("% +T\n", -4);
	len = printf("%% #T = ", -4);
	len = printf("% #T\n", -4);
	len = printf("%%+ T = ", -4);
	len = printf("%+ T\n", -4);
	len = printf("%%+#T = ", -4);
	len = printf("%+#T\n", -4);
	len = printf("%%# T = ", -4);
	len = printf("%# T\n", -4);
	len = printf("%%#+T = ", -4);
	len = printf("%#+T\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +#T = ", -4);
	len = printf("% +#T\n", -4);
	len = printf("%% #+T = ", -4);
	len = printf("% #+T\n", -4);
	len = printf("%%+# T = ", -4);
	len = printf("%+# T\n", -4);
	len = printf("%%+ #T = ", -4);
	len = printf("%+ #T\n", -4);
	len = printf("%%#+ T = ", -4);
	len = printf("%#+ T\n", -4);
	len = printf("%%# +T = ", -4);
	len = printf("%# +T\n", -4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");


	len = printf("%%u = ", -4);
	len = printf("%u\n", -4);
	len = printf("%% u = ", -4);
	len = printf("% u\n", -4);
	len = printf("%%#u = ", -4);
	len = printf("%#u\n", -4);
	len = printf("%%+u = ", -4);
	len = printf("%+u\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +u = ", -4);
	len = printf("% +u\n", -4);
	len = printf("%% #u = ", -4);
	len = printf("% #u\n", -4);
	len = printf("%%+ u = ", -4);
	len = printf("%+ u\n", -4);
	len = printf("%%+#u = ", -4);
	len = printf("%+#u\n", -4);
	len = printf("%%# u = ", -4);
	len = printf("%# u\n", -4);
	len = printf("%%#+u = ", -4);
	len = printf("%#+u\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +#u = ", -4);
	len = printf("% +#u\n", -4);
	len = printf("%% #+u = ", -4);
	len = printf("% #+u\n", -4);
	len = printf("%%+# u = ", -4);
	len = printf("%+# u\n", -4);
	len = printf("%%+ #u = ", -4);
	len = printf("%+ #u\n", -4);
	len = printf("%%#+ u = ", -4);
	len = printf("%#+ u\n", -4);
	len = printf("%%# +u = ", -4);
	len = printf("%# +u\n", -4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%o = ", -4);
	len = printf("%o\n", -4);
	len = printf("%% o = ", -4);
	len = printf("% o\n", -4);
	len = printf("%%#o = ", -4);
	len = printf("%#o\n", -4);
	len = printf("%%+o = ", -4);
	len = printf("%+o\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +o = ", -4);
	len = printf("% +o\n", -4);
	len = printf("%% #o = ", -4);
	len = printf("% #o\n", -4);
	len = printf("%%+ o = ", -4);
	len = printf("%+ o\n", -4);
	len = printf("%%+#o = ", -4);
	len = printf("%+#o\n", -4);
	len = printf("%%# o = ", -4);
	len = printf("%# o\n", -4);
	len = printf("%%#+o = ", -4);
	len = printf("%#+o\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +#o = ", -4);
	len = printf("% +#o\n", -4);
	len = printf("%% #+o = ", -4);
	len = printf("% #+o\n", -4);
	len = printf("%%+# o = ", -4);
	len = printf("%+# o\n", -4);
	len = printf("%%+ #o = ", -4);
	len = printf("%+ #o\n", -4);
	len = printf("%%#+ o = ", -4);
	len = printf("%#+ o\n", -4);
	len = printf("%%# +o = ", -4);
	len = printf("%# +o\n", -4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%x = ", -4);
	len = printf("%x\n", -4);
	len = printf("%% x = ", -4);
	len = printf("% x\n", -4);
	len = printf("%%#x = ", -4);
	len = printf("%#x\n", -4);
	len = printf("%%+x = ", -4);
	len = printf("%+x\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +x = ", -4);
	len = printf("% +x\n", -4);
	len = printf("%% #x = ", -4);
	len = printf("% #x\n", -4);
	len = printf("%%+ x = ", -4);
	len = printf("%+ x\n", -4);
	len = printf("%%+#x = ", -4);
	len = printf("%+#x\n", -4);
	len = printf("%%# x = ", -4);
	len = printf("%# x\n", -4);
	len = printf("%%#+x = ", -4);
	len = printf("%#+x\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +#x = ", -4);
	len = printf("% +#x\n", -4);
	len = printf("%% #+x = ", -4);
	len = printf("% #+x\n", -4);
	len = printf("%%+# x = ", -4);
	len = printf("%+# x\n", -4);
	len = printf("%%+ #x = ", -4);
	len = printf("%+ #x\n", -4);
	len = printf("%%#+ x = ", -4);
	len = printf("%#+ x\n", -4);
	len = printf("%%# +x = ", -4);
	len = printf("%# +x\n", -4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%X = ", -4);
	len = printf("%X\n", -4);
	len = printf("%% X = ", -4);
	len = printf("% X\n", -4);
	len = printf("%%#X = ", -4);
	len = printf("%#X\n", -4);
	len = printf("%%+X = ", -4);
	len = printf("%+X\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +X = ", -4);
	len = printf("% +X\n", -4);
	len = printf("%% #X = ", -4);
	len = printf("% #X\n", -4);
	len = printf("%%+ X = ", -4);
	len = printf("%+ X\n", -4);
	len = printf("%%+#X = ", -4);
	len = printf("%+#X\n", -4);
	len = printf("%%# X = ", -4);
	len = printf("%# X\n", -4);
	len = printf("%%#+X = ", -4);
	len = printf("%#+X\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +#X = ", -4);
	len = printf("% +#X\n", -4);
	len = printf("%% #+X = ", -4);
	len = printf("% #+X\n", -4);
	len = printf("%%+# X = ", -4);
	len = printf("%+# X\n", -4);
	len = printf("%%+ #X = ", -4);
	len = printf("%+ #X\n", -4);
	len = printf("%%#+ X = ", -4);
	len = printf("%#+ X\n", -4);
	len = printf("%%# +X = ", -4);
	len = printf("%# +X\n", -4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");



	len = printf("%%c = ", 'f');
	len = printf("%c\n", 'f');
	len = printf("%% c = ", 'f');
	len = printf("% c\n", 'f');
	len = printf("%%#c = ", 'f');
	len = printf("%#c\n", 'f');
	len = printf("%%+c = ", 'f');
	len = printf("%+c\n", 'f');
	len = printf("--------------------\n");
	len = printf("%% +c = ", 'f');
	len = printf("% +c\n", 'f');
	len = printf("%% #c = ", 'f');
	len = printf("% #c\n", 'f');
	len = printf("%%+ c = ", 'f');
	len = printf("%+ c\n", 'f');
	len = printf("%%+#c = ", 'f');
	len = printf("%+#c\n", 'f');
	len = printf("%%# c = ", 'f');
	len = printf("%# c\n", 'f');
	len = printf("%%#+c = ", 'f');
	len = printf("%#+c\n", 'f');
	len = printf("--------------------\n");
	len = printf("%% +#c = ", 'f');
	len = printf("% +#c\n", 'f');
	len = printf("%% #+c = ", 'f');
	len = printf("% #+c\n", 'f');
	len = printf("%%+# c = ", 'f');
	len = printf("%+# c\n", 'f');
	len = printf("%%+ #c = ", 'f');
	len = printf("%+ #c\n", 'f');
	len = printf("%%#+ c = ", 'f');
	len = printf("%#+ c\n", 'f');
	len = printf("%%# +c = ", 'f');
	len = printf("%# +c\n", 'f');
	len = printf("--------------------\n");
	len = printf("--------------------\n");


	len = printf("%%% = ", -4);
	len = printf("%%\n", -4);
	len = printf("%% % = ", -4);
	len = printf("% %\n", -4);
	len = printf("%%#% = ", -4);
	len = printf("%#%\n", -4);
	len = printf("%%+% = ", -4);
	len = printf("%+%\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +% = ", -4);
	len = printf("% +%\n", -4);
	len = printf("%% #% = ", -4);
	len = printf("% #%\n", -4);
	len = printf("%%+ % = ", -4);
	len = printf("%+ %\n", -4);
	len = printf("%%+#% = ", -4);
	len = printf("%+#%\n", -4);
	len = printf("%%# % = ", -4);
	len = printf("%# %\n", -4);
	len = printf("%%#+% = ", -4);
	len = printf("%#+%\n", -4);
	len = printf("--------------------\n");
	len = printf("%% +#% = ", -4);
	len = printf("% +#%\n", -4);
	len = printf("%% #+% = ", -4);
	len = printf("% #+%\n", -4);
	len = printf("%%+# % = ", -4);
	len = printf("%+# %\n", -4);
	len = printf("%%+ #% = ", -4);
	len = printf("%+ #%\n", -4);
	len = printf("%%#+ % = ", -4);
	len = printf("%#+ %\n", -4);
	len = printf("%%# +% = ", -4);
	len = printf("%# +%\n", -4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");



	len = printf("%%T = ", 0);
	len = printf("%T\n", 0);
	len = printf("%% T = ", 0);
	len = printf("% T\n", 0);
	len = printf("%%#T = ", 0);
	len = printf("%#T\n", 0);
	len = printf("%%+T = ", 0);
	len = printf("%+T\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +T = ", 0);
	len = printf("% +T\n", 0);
	len = printf("%% #T = ", 0);
	len = printf("% #T\n", 0);
	len = printf("%%+ T = ", 0);
	len = printf("%+ T\n", 0);
	len = printf("%%+#T = ", 0);
	len = printf("%+#T\n", 0);
	len = printf("%%# T = ", 0);
	len = printf("%# T\n", 0);
	len = printf("%%#+T = ", 0);
	len = printf("%#+T\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +#T = ", 0);
	len = printf("% +#T\n", 0);
	len = printf("%% #+T = ", 0);
	len = printf("% #+T\n", 0);
	len = printf("%%+# T = ", 0);
	len = printf("%+# T\n", 0);
	len = printf("%%+ #T = ", 0);
	len = printf("%+ #T\n", 0);
	len = printf("%%#+ T = ", 0);
	len = printf("%#+ T\n", 0);
	len = printf("%%# +T = ", 0);
	len = printf("%# +T\n", 0);
	len = printf("--------------------\n");
	len = printf("--------------------\n");


	len = printf("%%u = ", 0);
	len = printf("%u\n", 0);
	len = printf("%% u = ", 0);
	len = printf("% u\n", 0);
	len = printf("%%#u = ", 0);
	len = printf("%#u\n", 0);
	len = printf("%%+u = ", 0);
	len = printf("%+u\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +u = ", 0);
	len = printf("% +u\n", 0);
	len = printf("%% #u = ", 0);
	len = printf("% #u\n", 0);
	len = printf("%%+ u = ", 0);
	len = printf("%+ u\n", 0);
	len = printf("%%+#u = ", 0);
	len = printf("%+#u\n", 0);
	len = printf("%%# u = ", 0);
	len = printf("%# u\n", 0);
	len = printf("%%#+u = ", 0);
	len = printf("%#+u\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +#u = ", 0);
	len = printf("% +#u\n", 0);
	len = printf("%% #+u = ", 0);
	len = printf("% #+u\n", 0);
	len = printf("%%+# u = ", 0);
	len = printf("%+# u\n", 0);
	len = printf("%%+ #u = ", 0);
	len = printf("%+ #u\n", 0);
	len = printf("%%#+ u = ", 0);
	len = printf("%#+ u\n", 0);
	len = printf("%%# +u = ", 0);
	len = printf("%# +u\n", 0);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%o = ", 0);
	len = printf("%o\n", 0);
	len = printf("%% o = ", 0);
	len = printf("% o\n", 0);
	len = printf("%%#o = ", 0);
	len = printf("%#o\n", 0);
	len = printf("%%+o = ", 0);
	len = printf("%+o\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +o = ", 0);
	len = printf("% +o\n", 0);
	len = printf("%% #o = ", 0);
	len = printf("% #o\n", 0);
	len = printf("%%+ o = ", 0);
	len = printf("%+ o\n", 0);
	len = printf("%%+#o = ", 0);
	len = printf("%+#o\n", 0);
	len = printf("%%# o = ", 0);
	len = printf("%# o\n", 0);
	len = printf("%%#+o = ", 0);
	len = printf("%#+o\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +#o = ", 0);
	len = printf("% +#o\n", 0);
	len = printf("%% #+o = ", 0);
	len = printf("% #+o\n", 0);
	len = printf("%%+# o = ", 0);
	len = printf("%+# o\n", 0);
	len = printf("%%+ #o = ", 0);
	len = printf("%+ #o\n", 0);
	len = printf("%%#+ o = ", 0);
	len = printf("%#+ o\n", 0);
	len = printf("%%# +o = ", 0);
	len = printf("%# +o\n", 0);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%x = ", 0);
	len = printf("%x\n", 0);
	len = printf("%% x = ", 0);
	len = printf("% x\n", 0);
	len = printf("%%#x = ", 0);
	len = printf("%#x\n", 0);
	len = printf("%%+x = ", 0);
	len = printf("%+x\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +x = ", 0);
	len = printf("% +x\n", 0);
	len = printf("%% #x = ", 0);
	len = printf("% #x\n", 0);
	len = printf("%%+ x = ", 0);
	len = printf("%+ x\n", 0);
	len = printf("%%+#x = ", 0);
	len = printf("%+#x\n", 0);
	len = printf("%%# x = ", 0);
	len = printf("%# x\n", 0);
	len = printf("%%#+x = ", 0);
	len = printf("%#+x\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +#x = ", 0);
	len = printf("% +#x\n", 0);
	len = printf("%% #+x = ", 0);
	len = printf("% #+x\n", 0);
	len = printf("%%+# x = ", 0);
	len = printf("%+# x\n", 0);
	len = printf("%%+ #x = ", 0);
	len = printf("%+ #x\n", 0);
	len = printf("%%#+ x = ", 0);
	len = printf("%#+ x\n", 0);
	len = printf("%%# +x = ", 0);
	len = printf("%# +x\n", 0);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%X = ", 0);
	len = printf("%X\n", 0);
	len = printf("%% X = ", 0);
	len = printf("% X\n", 0);
	len = printf("%%#X = ", 0);
	len = printf("%#X\n", 0);
	len = printf("%%+X = ", 0);
	len = printf("%+X\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +X = ", 0);
	len = printf("% +X\n", 0);
	len = printf("%% #X = ", 0);
	len = printf("% #X\n", 0);
	len = printf("%%+ X = ", 0);
	len = printf("%+ X\n", 0);
	len = printf("%%+#X = ", 0);
	len = printf("%+#X\n", 0);
	len = printf("%%# X = ", 0);
	len = printf("%# X\n", 0);
	len = printf("%%#+X = ", 0);
	len = printf("%#+X\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +#X = ", 0);
	len = printf("% +#X\n", 0);
	len = printf("%% #+X = ", 0);
	len = printf("% #+X\n", 0);
	len = printf("%%+# X = ", 0);
	len = printf("%+# X\n", 0);
	len = printf("%%+ #X = ", 0);
	len = printf("%+ #X\n", 0);
	len = printf("%%#+ X = ", 0);
	len = printf("%#+ X\n", 0);
	len = printf("%%# +X = ", 0);
	len = printf("%# +X\n", 0);
	len = printf("--------------------\n");
	len = printf("--------------------\n");



	len = printf("%%c = ", 'f');
	len = printf("%c\n", 'f');
	len = printf("%% c = ", 'f');
	len = printf("% c\n", 'f');
	len = printf("%%#c = ", 'f');
	len = printf("%#c\n", 'f');
	len = printf("%%+c = ", 'f');
	len = printf("%+c\n", 'f');
	len = printf("--------------------\n");
	len = printf("%% +c = ", 'f');
	len = printf("% +c\n", 'f');
	len = printf("%% #c = ", 'f');
	len = printf("% #c\n", 'f');
	len = printf("%%+ c = ", 'f');
	len = printf("%+ c\n", 'f');
	len = printf("%%+#c = ", 'f');
	len = printf("%+#c\n", 'f');
	len = printf("%%# c = ", 'f');
	len = printf("%# c\n", 'f');
	len = printf("%%#+c = ", 'f');
	len = printf("%#+c\n", 'f');
	len = printf("--------------------\n");
	len = printf("%% +#c = ", 'f');
	len = printf("% +#c\n", 'f');
	len = printf("%% #+c = ", 'f');
	len = printf("% #+c\n", 'f');
	len = printf("%%+# c = ", 'f');
	len = printf("%+# c\n", 'f');
	len = printf("%%+ #c = ", 'f');
	len = printf("%+ #c\n", 'f');
	len = printf("%%#+ c = ", 'f');
	len = printf("%#+ c\n", 'f');
	len = printf("%%# +c = ", 'f');
	len = printf("%# +c\n", 'f');
	len = printf("--------------------\n");
	len = printf("--------------------\n");


	len = printf("%%% = ", 0);
	len = printf("%%\n", 0);
	len = printf("%% % = ", 0);
	len = printf("% %\n", 0);
	len = printf("%%#% = ", 0);
	len = printf("%#%\n", 0);
	len = printf("%%+% = ", 0);
	len = printf("%+%\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +% = ", 0);
	len = printf("% +%\n", 0);
	len = printf("%% #% = ", 0);
	len = printf("% #%\n", 0);
	len = printf("%%+ % = ", 0);
	len = printf("%+ %\n", 0);
	len = printf("%%+#% = ", 0);
	len = printf("%+#%\n", 0);
	len = printf("%%# % = ", 0);
	len = printf("%# %\n", 0);
	len = printf("%%#+% = ", 0);
	len = printf("%#+%\n", 0);
	len = printf("--------------------\n");
	len = printf("%% +#% = ", 0);
	len = printf("% +#%\n", 0);
	len = printf("%% #+% = ", 0);
	len = printf("% #+%\n", 0);
	len = printf("%%+# % = ", 0);
	len = printf("%+# %\n", 0);
	len = printf("%%+ #% = ", 0);
	len = printf("%+ #%\n", 0);
	len = printf("%%#+ % = ", 0);
	len = printf("%#+ %\n", 0);
	len = printf("%%# +% = ", 0);
	len = printf("%# +%\n", 0);
	len = printf("--------------------\n");
	len = printf("--------------------\n");



	return (len);
}
