#include <stdio.h>
#include "../holberton.h"
int main()
{
	int len;
	len = printf("%%T = ", 4);
	len = printf("%T\n", 4);
	len = printf("%% T = ", 4);
	len = printf("% T\n", 4);
	len = printf("%%#T = ", 4);
	len = printf("%#T\n", 4);
	len = printf("%%+T = ", 4);
	len = printf("%+T\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +T = ", 4);
	len = printf("% +T\n", 4);
	len = printf("%% #T = ", 4);
	len = printf("% #T\n", 4);
	len = printf("%%+ T = ", 4);
	len = printf("%+ T\n", 4);
	len = printf("%%+#T = ", 4);
	len = printf("%+#T\n", 4);
	len = printf("%%# T = ", 4);
	len = printf("%# T\n", 4);
	len = printf("%%#+T = ", 4);
	len = printf("%#+T\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#T = ", 4);
	len = printf("% +#T\n", 4);
	len = printf("%% #+T = ", 4);
	len = printf("% #+T\n", 4);
	len = printf("%%+# T = ", 4);
	len = printf("%+# T\n", 4);
	len = printf("%%+ #T = ", 4);
	len = printf("%+ #T\n", 4);
	len = printf("%%#+ T = ", 4);
	len = printf("%#+ T\n", 4);
	len = printf("%%# +T = ", 4);
	len = printf("%# +T\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");


	len = printf("%%u = ", 4);
	len = printf("%u\n", 4);
	len = printf("%% u = ", 4);
	len = printf("% u\n", 4);
	len = printf("%%#u = ", 4);
	len = printf("%#u\n", 4);
	len = printf("%%+u = ", 4);
	len = printf("%+u\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +u = ", 4);
	len = printf("% +u\n", 4);
	len = printf("%% #u = ", 4);
	len = printf("% #u\n", 4);
	len = printf("%%+ u = ", 4);
	len = printf("%+ u\n", 4);
	len = printf("%%+#u = ", 4);
	len = printf("%+#u\n", 4);
	len = printf("%%# u = ", 4);
	len = printf("%# u\n", 4);
	len = printf("%%#+u = ", 4);
	len = printf("%#+u\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#u = ", 4);
	len = printf("% +#u\n", 4);
	len = printf("%% #+u = ", 4);
	len = printf("% #+u\n", 4);
	len = printf("%%+# u = ", 4);
	len = printf("%+# u\n", 4);
	len = printf("%%+ #u = ", 4);
	len = printf("%+ #u\n", 4);
	len = printf("%%#+ u = ", 4);
	len = printf("%#+ u\n", 4);
	len = printf("%%# +u = ", 4);
	len = printf("%# +u\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%o = ", 4);
	len = printf("%o\n", 4);
	len = printf("%% o = ", 4);
	len = printf("% o\n", 4);
	len = printf("%%#o = ", 4);
	len = printf("%#o\n", 4);
	len = printf("%%+o = ", 4);
	len = printf("%+o\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +o = ", 4);
	len = printf("% +o\n", 4);
	len = printf("%% #o = ", 4);
	len = printf("% #o\n", 4);
	len = printf("%%+ o = ", 4);
	len = printf("%+ o\n", 4);
	len = printf("%%+#o = ", 4);
	len = printf("%+#o\n", 4);
	len = printf("%%# o = ", 4);
	len = printf("%# o\n", 4);
	len = printf("%%#+o = ", 4);
	len = printf("%#+o\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#o = ", 4);
	len = printf("% +#o\n", 4);
	len = printf("%% #+o = ", 4);
	len = printf("% #+o\n", 4);
	len = printf("%%+# o = ", 4);
	len = printf("%+# o\n", 4);
	len = printf("%%+ #o = ", 4);
	len = printf("%+ #o\n", 4);
	len = printf("%%#+ o = ", 4);
	len = printf("%#+ o\n", 4);
	len = printf("%%# +o = ", 4);
	len = printf("%# +o\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%x = ", 4);
	len = printf("%x\n", 4);
	len = printf("%% x = ", 4);
	len = printf("% x\n", 4);
	len = printf("%%#x = ", 4);
	len = printf("%#x\n", 4);
	len = printf("%%+x = ", 4);
	len = printf("%+x\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +x = ", 4);
	len = printf("% +x\n", 4);
	len = printf("%% #x = ", 4);
	len = printf("% #x\n", 4);
	len = printf("%%+ x = ", 4);
	len = printf("%+ x\n", 4);
	len = printf("%%+#x = ", 4);
	len = printf("%+#x\n", 4);
	len = printf("%%# x = ", 4);
	len = printf("%# x\n", 4);
	len = printf("%%#+x = ", 4);
	len = printf("%#+x\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#x = ", 4);
	len = printf("% +#x\n", 4);
	len = printf("%% #+x = ", 4);
	len = printf("% #+x\n", 4);
	len = printf("%%+# x = ", 4);
	len = printf("%+# x\n", 4);
	len = printf("%%+ #x = ", 4);
	len = printf("%+ #x\n", 4);
	len = printf("%%#+ x = ", 4);
	len = printf("%#+ x\n", 4);
	len = printf("%%# +x = ", 4);
	len = printf("%# +x\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%X = ", 4);
	len = printf("%X\n", 4);
	len = printf("%% X = ", 4);
	len = printf("% X\n", 4);
	len = printf("%%#X = ", 4);
	len = printf("%#X\n", 4);
	len = printf("%%+X = ", 4);
	len = printf("%+X\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +X = ", 4);
	len = printf("% +X\n", 4);
	len = printf("%% #X = ", 4);
	len = printf("% #X\n", 4);
	len = printf("%%+ X = ", 4);
	len = printf("%+ X\n", 4);
	len = printf("%%+#X = ", 4);
	len = printf("%+#X\n", 4);
	len = printf("%%# X = ", 4);
	len = printf("%# X\n", 4);
	len = printf("%%#+X = ", 4);
	len = printf("%#+X\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#X = ", 4);
	len = printf("% +#X\n", 4);
	len = printf("%% #+X = ", 4);
	len = printf("% #+X\n", 4);
	len = printf("%%+# X = ", 4);
	len = printf("%+# X\n", 4);
	len = printf("%%+ #X = ", 4);
	len = printf("%+ #X\n", 4);
	len = printf("%%#+ X = ", 4);
	len = printf("%#+ X\n", 4);
	len = printf("%%# +X = ", 4);
	len = printf("%# +X\n", 4);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	len = printf("%%i = ", 4);
	len = printf("%i\n", 4);
	len = printf("%% i = ", 4);
	len = printf("% i\n", 4);
	len = printf("%%#i = ", 4);
	len = printf("%#i\n", 4);
	len = printf("%%+i = ", 4);
	len = printf("%+i\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +i = ", 4);
	len = printf("% +i\n", 4);
	len = printf("%% #i = ", 4);
	len = printf("% #i\n", 4);
	len = printf("%%+ i = ", 4);
	len = printf("%+ i\n", 4);
	len = printf("%%+#i = ", 4);
	len = printf("%+#i\n", 4);
	len = printf("%%# i = ", 4);
	len = printf("%# i\n", 4);
	len = printf("%%#+i = ", 4);
	len = printf("%#+i\n", 4);
	len = printf("--------------------\n");
	len = printf("%% +#i = ", 4);
	len = printf("% +#i\n", 4);
	len = printf("%% #+i = ", 4);
	len = printf("% #+i\n", 4);
	len = printf("%%+# i = ", 4);
	len = printf("%+# i\n", 4);
	len = printf("%%+ #i = ", 4);
	len = printf("%+ #i\n", 4);
	len = printf("%%#+ i = ", 4);
	len = printf("%#+ i\n", 4);
	len = printf("%%# +i = ", 0);
	len = printf("%# +i\n", -1);
	len = printf("--------------------\n");
	len = printf("--------------------\n");

	return (len);
}
